version: 2.1
api-version: 1.20
name: EntityCleaner
main: snatev.entity_cleaner.EntityCleaner

commands:
  ecl:
    permission: entitycleaner.command
    description: Manage EntityCleaner
    usage: /ecl <pause|resume|status|broadcast|reload>
