version: 2.1
api-version: 1.20
name: IPWhitelist
main: snatev.ipwhitelist.IPWhitelist

commands:
  ipw:
    permission: ipwhitelist.command
    description: Manage IPWhitelist
    usage: /ipw <enable|disable|status|reload|list>
