version: 1.1
api-version: 1.20
name: EndermanGuard
main: snatev.endermanguard.EndermanGuard

commands:
  emg:
    permission: endermanguard.command
    description: Manage EndermanGuard
    usage: /emg <enable|disable|status|reload>
